name: Build

on:
  #push:
  #  branches:
  #    - main
  release:
    types: [ created ]
  #pull_request:
  #  types: [ opened, synchronize, reopened ]
  workflow_dispatch:

permissions: {}

jobs:
  build:
    name: Build
    permissions:
      contents: read
    runs-on: [ windows-latest ]

    steps:
    - name: Get latest CMake and ninja
      uses: lukka/get-cmake@latest

    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup VS environment
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Build and install debug
      run: |
        cmake --preset x64-Debug .
        cmake --build _build/x64-Debug --parallel
        cmake --install _build/x64-Debug

    - name: Build and install release
      run: |
        cmake --preset x64-Release .
        cmake --build _build/x64-Release --parallel
        cmake --install _build/x64-Release

    - name: Copy debug artifacts
      run: |
        mkdir _dist-debug
        Copy-Item _install/x64-Debug/bin/* -Destination _dist-debug/ -Recurse
        Copy-Item LICENSE -Destination _dist-debug/LICENSE

    - name: Copy release artifacts
      run: |
        mkdir _dist-release
        Copy-Item _install/x64-Release/bin/* -Destination _dist-release/ -Recurse
        Copy-Item LICENSE -Destination _dist-release/LICENSE

    - name: Archive debug
      uses: actions/upload-artifact@v4
      with:
        name: ChaosMod-Debug
        path: _dist-debug/*

    - name: Archive release
      uses: actions/upload-artifact@v4
      with:
        name: ChaosMod-Release
        path: _dist-release/*

  upload_release:
    name: Upload release artifacts
    needs: build
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Download debug artifact
      uses: actions/download-artifact@v4
      with:
        name: ChaosMod-Debug
        path: ChaosMod-Debug

    - name: Download release artifact
      uses: actions/download-artifact@v4
      with:
        name: ChaosMod-Release
        path: ChaosMod-Release

    - name: Archive artifact files
      run: |
        cd ChaosMod-Debug
        zip -r ChaosMod-Debug.zip *
        cd ../ChaosMod-Release
        zip -r ChaosMod-Release.zip *

    - name: Upload the files to release
      uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # 2.5.0
      with:
        files: |
          ChaosMod-Debug/ChaosMod-Debug.zip
          ChaosMod-Release/ChaosMod-Release.zip
